/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.87
 * Generated at: 2024-04-23 08:05:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class updateForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1713773717000L));
    _jspx_dependants.put("/WEB-INF/board/../pages/header.jsp", Long.valueOf(1713836581000L));
    _jspx_dependants.put("jar:file:/Users/cano/Desktop/git_study/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/JSPClassCh0610/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("/WEB-INF/board/../pages/footer.jsp", Long.valueOf(1713836717000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("<link href=\"bootstrap/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("<script src=\"js/jquery-3.7.1.min.js\"></script>\n");
      out.write("<script src=\"js/formCheck02.js\"></script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<div class=\"container\">\n");
      out.write("		<!-- header -->\n");
      out.write("		");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<div class=\"row border-bottom border-primary\">\n");
      out.write("			<div class=\"col-4\">\n");
      out.write("				<img src=\"https://via.placeholder.com/200x100\">\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("			<div class=\"col-8\">\n");
      out.write("				<div class=\"row\">\n");
      out.write("					<div class=\"col\">\n");
      out.write("						<ul class=\"nav justify-content-end\">\n");
      out.write("							<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">로그인</a></li>\n");
      out.write("							<li class=\"nav-item\"><a class=\"nav-link\" href=\"boardList\">게시글\n");
      out.write("									리스트 </a></li>\n");
      out.write("							<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">회원가입</a></li>\n");
      out.write("							<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">주문/배송조회\n");
      out.write("							</a></li>\n");
      out.write("							<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">고객센터 </a></li>\n");
      out.write("\n");
      out.write("						</ul>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"row\">\n");
      out.write("					<div class=\"col text-end\">로그인 시 인사말 출력 </div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\n");
      out.write("		<!-- content -->\n");
      out.write("		<div class=\"row my-5\" id=\"global-content\">\n");
      out.write("			<div class= \"col\">\n");
      out.write("				<div class=\"row\">\n");
      out.write("					<div class=\"col\">\n");
      out.write("						<h1 class=\"text-center fw-bold fs-3\">게시 글 수정하기</h1>\n");
      out.write("					</div>			\n");
      out.write("				</div>				\n");
      out.write("				<form name=\"updateForm\" id=\"updateForm\" action=\"updateProcess\" \n");
      out.write("					method=\"post\" class=\"row border-primary g-3 my-3\">\n");
      out.write("					<input type=\"hidden\" name=\"no\" id=\"no\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.no }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">										\n");
      out.write("					<div class=\"col-4 offset-2\">\n");
      out.write("					    <label for=\"writer\" class=\"form-label\">글쓴이</label>\n");
      out.write("					    <input type=\"text\" class=\"form-control\" id=\"writer\" name=\"writer\"\n");
      out.write("				     	readonly value =\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.writer }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"placeholder=\"작성자를 입력해 주세요\">\n");
      out.write("				  	</div>\n");
      out.write("				  	<div class=\"col-4\">\n");
      out.write("					    <label for=\"pass\" class=\"form-label\">비밀번호</label>\n");
      out.write("					    <input type=\"password\" class=\"form-control\" id=\"pass\" name=\"pass\">\n");
      out.write("				  	</div>\n");
      out.write("					<div class=\"col-8 offset-2\">\n");
      out.write("					    <label for=\"title\" class=\"form-label\">제 목</label>\n");
      out.write("					    <input type=\"text\" class=\"form-control\" id=\"title\" name=\"title\"\n");
      out.write("					    	value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("				  	</div>\n");
      out.write("					<div class=\"col-8 offset-2\">\n");
      out.write("					    <label for=\"content\" class=\"form-label\">내 용</label>\n");
      out.write("					    <textarea class=\"form-control\" id=\"content\" name=\"content\" \n");
      out.write("					    	rows=\"10\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.content }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea>\n");
      out.write("				  	</div>\n");
      out.write("					<div class=\"col-8 offset-2 text-center mt-5\">					   \n");
      out.write("					    <input type=\"submit\" value=\"등록하기\" class=\"btn btn-primary\">\n");
      out.write("					    &nbsp;&nbsp;\n");
      out.write("					    <input type=\"button\" value=\"목록보기\" class=\"btn btn-primary\"\n");
      out.write("					    	onclick=\"location.href='boardList'\">\n");
      out.write("				  	</div>				  	\n");
      out.write("				</form>				\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		<!-- footer -->\n");
      out.write("		");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<div class=\"row my-5 border-top border-primary\" id=\"footer\">\n");
      out.write("		<div class=\"col text-center py-3\">\n");
      out.write("			<p>\n");
      out.write("				고객상담 전화주문 : 1234-5678 사업자등록번호 : 111-11-123456 대표이사 : 홍길동 통신판매업 서울 제\n");
      out.write("				000000호<br> 개인정보관리책입자 : 임꺽정 분쟁조정기관표시 : 소비자보호원, 전자거래분재중재위원회<br>\n");
      out.write("				Copyright (c) 2023 JSP2U Corp. All right Reserved.\n");
      out.write("			</p>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\n");
      out.write("		<script src=\"bootstrap/bootstrap.bundle.min.js\"></script>\n");
      out.write("	</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
